name = "generator"
version = "0.1.0"
defaultTargets = ["generator"]

[[lean_lib]]
name = "Generator"
srcDir = "Generator"

[[lean_lib]]
name = "Helper"
srcDir = "Generator"

[[lean_exe]]
name = "generator"
root = "GenerateTestFile"
