name = "affine-cipher"
version = "0.1.0"
defaultTargets = ["AffineCipherTest"]
testDriver = "AffineCipherTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "AffineCipher"

[[lean_exe]]
name = "AffineCipherTest"
root = "AffineCipherTest"
